{
 "title": "Email Log Dashboard",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "エラーメール件数 (24時間)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"email-routing\", level=\"error\"} [24h])"
    }
   ]
  },
  {
   "title": "エラーメール一覧",
   "type": "table",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"email-routing\", level=\"error\"}"
    }
   ]
  },
  {
   "title": "エラーメール件数 (14日)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"email-routing\", level=\"error\"} [14d])"
    }
   ]
  },
  {
   "title": "Email Log Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({service_name=\"email-routing\"} [1h]))"
    }
   ]
  }
 ]
}